# Generated by Django 6.0.1 on 2026-01-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Finance Printer', max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('model_name', models.CharField(blank=True, help_text='Auto-detected model', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Uncheck to stop polling this device')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_pages', models.IntegerField(null=True)),
                ('status', models.CharField(default='Unknown', max_length=50)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.printer')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('level_percent', models.IntegerField()),
                ('max_capacity', models.IntegerField(null=True)),
                ('current_level', models.IntegerField(null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='devices.printerlog')),
            ],
        ),
    ]
