# Generated by Django 4.2.6 on 2026-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Physical address for conflict detection', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., Finance Printer', max_length=100),
        ),
    ]
