# Generated by Django 4.2.6 on 2026-01-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_printer_mac_address_alter_printer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Printer', 'verbose_name_plural': 'Printers'},
        ),
        migrations.AlterModelOptions(
            name='printerlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Printer Log', 'verbose_name_plural': 'Printer Logs'},
        ),
        migrations.AlterModelOptions(
            name='supplylevel',
            options={'verbose_name': 'Supply Level', 'verbose_name_plural': 'Supply Levels'},
        ),
        migrations.AddField(
            model_name='printer',
            name='cost_per_page_color',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='cost_per_page_mono',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='energy_consumption_rate_watts',
            field=models.IntegerField(blank=True, help_text='Typical power draw in watts', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='maintenance_kit_capacity',
            field=models.IntegerField(blank=True, help_text='Pages between maintenance kit replacement', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='target_monthly_volume',
            field=models.IntegerField(blank=True, help_text='Expected monthly page count target', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='error_code',
            field=models.CharField(blank=True, help_text='Vendor-specific error code, e.g., 40.00.01', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='event_type',
            field=models.CharField(choices=[('STATUS_CHECK', 'Status Check'), ('PAPER_JAM', 'Paper Jam'), ('LOW_TONER', 'Low Toner'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='STATUS_CHECK', max_length=20),
        ),
        migrations.AlterField(
            model_name='printerlog',
            name='status',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='PrinterDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_pages_printed', models.IntegerField(default=0)),
                ('jam_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('uptime_minutes', models.IntegerField(default=0)),
                ('idle_minutes', models.IntegerField(default=0)),
                ('downtime_minutes', models.IntegerField(default=0)),
                ('energy_usage_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='devices.printer')),
            ],
            options={
                'verbose_name': 'Printer Daily Stat',
                'verbose_name_plural': 'Printer Daily Stats',
                'ordering': ['-date'],
                'unique_together': {('printer', 'date')},
            },
        ),
    ]
