# Generated by Django 4.2.6 on 2026-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_enterprise_fleet_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerlog',
            name='system_uptime_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
