# Generated by Django 4.2.6 on 2026-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_add_system_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='active_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='console_display',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printerlog',
            name='tray_status',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
