# Generated by Django 4.2.6 on 2026-01-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_printer_firmware_version_printer_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='sys_name',
            field=models.CharField(blank=True, help_text='Hostname (SNMP sysName)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='location',
            field=models.CharField(blank=True, help_text='SNMP sysLocation', max_length=255),
        ),
        migrations.AlterField(
            model_name='printerlog',
            name='tray_status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
