# Generated by Django 4.2.6 on 2026-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_add_sys_name_and_tray_status_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='current_status',
            field=models.IntegerField(blank=True, choices=[(3, 'Idle'), (4, 'Printing'), (5, 'Warming Up')], help_text='3=Idle, 4=Printing, 5=Warming Up', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='device_health',
            field=models.IntegerField(blank=True, choices=[(2, 'Running'), (3, 'Warning'), (5, 'Down')], help_text='2=Running, 3=Warning, 5=Down', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, help_text='When this device was last polled via SNMP', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='total_page_count',
            field=models.BigIntegerField(blank=True, help_text='Lifetime page count from printer', null=True),
        ),
    ]
