# Generated by Django 4.2.6 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_add_realtime_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='alert_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='is_in_alert_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='last_latency_ms',
            field=models.IntegerField(blank=True, help_text='SNMP response time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='min_supply_percent',
            field=models.IntegerField(blank=True, help_text='Lowest supply/toner level from last poll (for SRE saturation)', null=True),
        ),
        migrations.AddField(
            model_name='printerdailystat',
            name='avg_latency_ms',
            field=models.IntegerField(default=0),
        ),
    ]
