# Generated by Django 4.2.6 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_add_sre_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="last_serviced_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="next_servicing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="printerdailystat",
            name="jams_today",
            field=models.IntegerField(default=0, help_text="Paper jams this day"),
        ),
        migrations.AddField(
            model_name="printerdailystat",
            name="pages_printed_today",
            field=models.IntegerField(default=0, help_text="Pages printed this day"),
        ),
        migrations.AddField(
            model_name="printerdailystat",
            name="sleep_time_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
