# Generated by Django 5.2.12 on 2026-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_optimize_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='printer',
            name='devices_pri_active_health_idx',
        ),
        migrations.RemoveIndex(
            model_name='printer',
            name='devices_pri_active_supply_idx',
        ),
        migrations.RemoveIndex(
            model_name='printerlog',
            name='devices_log_printer_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='printerlog',
            name='devices_log_event_ts_idx',
        ),
        migrations.AlterField(
            model_name='consumable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
