# Generated by Django 4.2.6 on 2026-03-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='current_status',
            field=models.IntegerField(blank=True, choices=[(2, 'Sleeping'), (3, 'Idle'), (4, 'Printing'), (5, 'Warming Up')], help_text='3=Idle, 4=Printing, 5=Warming Up', null=True),
        ),
    ]
